# Generated by Django 5.2 on 2025-06-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EffectGroup",
            fields=[
                (
                    "effect_group_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("effect_group", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("form_id", models.AutoField(primary_key=True, serialize=False)),
                ("form_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("institution_id", models.AutoField(primary_key=True, serialize=False)),
                ("institution", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionIssuance",
            fields=[
                ("issuance_id", models.AutoField(primary_key=True, serialize=False)),
                ("issuance_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                ("shelf_id", models.AutoField(primary_key=True, serialize=False)),
                ("shelf_location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                ("medicine_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.company",
                    ),
                ),
                (
                    "effect_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.effectgroup",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharmacy.form"
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.prescriptionissuance",
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.shelf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineSale",
            fields=[
                ("sale_id", models.AutoField(primary_key=True, serialize=False)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("sale_date", models.DateTimeField(auto_now_add=True)),
                ("barcode", models.CharField(max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.customer",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pharmacy.institution",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medicine",
                    ),
                ),
            ],
        ),
    ]
